### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nathanstitt**
A few tweaks to support ActiveRecord 4.2 now that Lanes is moving to it.  I also found an omission on the parent_class spec, where it needs to be set as an abstract_class.

### CODE REVIEW

**Comment by envygeeks** [comment]
Have you confirmed that this does not break support for 3.2 - 4.1? While Rails does not support 3.2 past security right now, we still have production apps that have yet to upgrade to 4.2 from 3.2 so it's dire that support remain for a minor release.

**Comment by nathanstitt** [comment]
I ran the test suite with ActiveRecord 4.1, but not 3.2.  I'll investigate that and get back to you

**Comment by nathanstitt** [comment]
Sorry for the delay, this got pushed to the back of the queue.

Ok, I've tested with ActiveRecord 3.2.  The reflect_on_association method of retrieving the associations is present and works file.

I did discover an unrelated bug with 3.2 though.  The "enables extensions" spec failed.  It looked to me like perhaps it was expecting an exception to be raised, but none was.   I didn't investigate further since it was unrelated to the PR, but figured I should mention it so you'd be aware.

**Comment by envygeeks** [comment]
There might be a bug in the spec I shall check it out.  Thanks! :heart:

**Pull request merged**
